name: Build and deploy

on:
  push:
    branches:
      - master
  release:
    types: [created]

env:
  GIT_USER: 'GitHub Actions'
  GIT_EMAIL: '41898282+github-actions[bot]@users.noreply.github.com'
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-node@v1
        with:
          node-version: 8.4
      - name: Pull latest
        run: git pull origin master
      - name: Install dependencies
        run: yarn
      - name: Build application
        run: yarn build
      - name: Run linter
        run: yarn lint
      - name: Run tests
        run: yarn test:coverage
    #   - name: Report coverage
    #     run: yarn codecov
      - name: Create CNAME Record
        run: echo "tycho.io" > build/CNAME
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_CONFIG_NAME: ${{ env.GIT_USER }}
          GIT_CONFIG_EMAIL: ${{ env.GIT_EMAIL }}
          BRANCH: gh-pages
          FOLDER: build
          CLEAN: true
